server:
  port: 8888

spring:
  redis-limiter:
      redis-host: 127.0.0.1
      check-action-timeout: 100
      enable-dynamical-conf: true

user-based-permits:
  userid.user1: 5
  userid.user2: 10